// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

#define GROUP_SIZE 256

struct MyBufferData {
    float3 position;
    float padding0;
};

RWStructuredBuffer<MyBufferData> sharedBuffer;

[numthreads(GROUP_SIZE,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    uint index = id.x;
    MyBufferData data = sharedBuffer[index];
    data.position += float3(0.002 * index, 0, 0);
    sharedBuffer[index] = data;
}
